//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5420
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paycenter_sdk {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Paycenter_sdk.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 cert/epaylinks_pfx.cer 的本地化字符串。
        /// </summary>
        internal static string CER_PATH {
            get {
                return ResourceManager.GetString("CER_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UTF-8 的本地化字符串。
        /// </summary>
        internal static string ENCODING {
            get {
                return ResourceManager.GetString("ENCODING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://14.23.90.100:443/paycenter/gateways.do 的本地化字符串。
        /// </summary>
        internal static string ORDER_URL {
            get {
                return ResourceManager.GetString("ORDER_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 130 的本地化字符串。
        /// </summary>
        internal static string PARTNER {
            get {
                return ResourceManager.GetString("PARTNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://14.23.90.100/paycenter/v2.0/getoi.do 的本地化字符串。
        /// </summary>
        internal static string PAY_URL {
            get {
                return ResourceManager.GetString("PAY_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 cert/yzt.pfx 的本地化字符串。
        /// </summary>
        internal static string PFX_PATH {
            get {
                return ResourceManager.GetString("PFX_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yzt20160728 的本地化字符串。
        /// </summary>
        internal static string PRIVATEKEY_PASSWORD {
            get {
                return ResourceManager.GetString("PRIVATEKEY_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SHA256withRSA 的本地化字符串。
        /// </summary>
        internal static string SIGN_TYPE {
            get {
                return ResourceManager.GetString("SIGN_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4.0 的本地化字符串。
        /// </summary>
        internal static string VERSION {
            get {
                return ResourceManager.GetString("VERSION", resourceCulture);
            }
        }
    }
}
